version: '3'

services:
  frontend:
    image: sousagd/frontend-app:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: sousagd/backend-app:latest
    container_name: backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
